name: Terraform Workflow

on:
  push:
    branches:
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Use the version of Terraform you need

    - name: Initialize Terraform
      run: terraform init 

    - name: Validate Terraform
      run: terraform validate 

    - name: Plan Terraform
      run: terraform plan -input=false -out=tfplan

    - name: Apply Terraform
      run: terraform apply -input=false tfplan -auto-approve      

    - name: Clean up Terraform files
      run: rm -f tfplan
